apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx
  # these labels belongs to replicaset resources
  labels:
    app: nginx
    tier: frontend
spec: 
#modify replicaa according to your case
  replicas: 3
  selector:
    matchLabels:
      tier: frontend
      app: nginx
      #below is pod definition
  template:
    metadata:
      labels:
        tier: frontend
        app: nginx
        project: test-project
    spec:
      containers:
      - name: nginx
        image: nginx       
