kind: Pod
apiVersion: v1
metadata:
   name: env
spec: 
  containers:
  - name: nginx
    image: nginx
    env:
    - name: course
      value: 'kuberenetes'
    - name: duration
      value: '20hours'